Traceback (most recent call last):
  File "/disk/u/lofty/GPTNext/experiments/_08_rmsnorm_train.py", line 125, in <module>
    data_dir = os.path.join('../data', dataset); assert os.path.exists(data_dir)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
